config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'
  resources :cocktails, except: [:destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
  accepts_nested_attributes_for :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :cocktail, scope: :ingredient
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :coctails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :cocktail_by_id, only: [:show, :edit, :update]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(strong_params_cocktails)
    if @cocktail.save
      params['cocktail']['ingredient_ids'][(1..-1)].each do |id|
        dose = Dose.new()
        dose.description = params['cocktail'][id]
        dose.cocktail = @cocktail
        dose.ingredient_id = id
        unless dose.save
          @doses = @cocktail.doses
          return render :new
        end
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @doses = @cocktail.doses
  end

  def update
    if @cocktail.update(strong_params_cocktails)
      params['cocktail']['doses_attributes'].each do |id|
        dose = @cocktail.doses.find(id[1]['id'].to_i)
        dose.description = id[1]['description']
        dose.cocktail = @cocktail
        dose.save
      end
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def strong_params_cocktails
    params.require(:cocktail).permit(:name, :instructions, :photo)
  end

  def cocktail_by_id
    @cocktail = Cocktail.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :instructions %>
  <% if @cocktail.photo.present? %>
    <%= cl_image_tag @cocktail.photo, width: 200, class: "my-2" %>
  <% end %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.association :ingredients %>
  <%= f.simple_fields_for :doses do |ff| %>
    <%= ff.input :description %>
  <% end %>
  <div class="ingredient_descriptions">
  </div>
  <%= f.button :submit, class: "btn btn-success mt-3" %>
  <%= link_to 'cancel', root_path, class: "btn btn-danger mt-3"  %>
<% end %>


<%#= simple_form_for @cocktail do |f| %>
  <%#= f.input :name %>
  <%#= f.input :instructions %>
  <%# if @cocktail.photo.present? %>
    <%#= cl_image_tag @cocktail.photo, width: 200, class: "my-2" %>
  <%# end %>
  <%#= f.input :photo %>
  <%#= f.input :photo_cache, as: :hidden %>
  <%#= f.simple_fields_for Cocktail.new do |c| %>
    <%#= c.association :ingredients %>
  <%# end %>
  <%#= f.simple_fields_for :doses do |ff| %>
    <%#= ff.input :description %>
  <%# end %>
  <!-- <div class="ingredient_descriptions">
  </div> -->
  <%#= f.button :submit, class: "btn btn-success mt-3" %>
  <%#= link_to 'cancel', root_path, class: "btn btn-danger mt-3"  %>
<%# end %>

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="cards">
        <% @cocktails.each do |ct| %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= ct.photo.present? ? (cl_image_path ct.photo) : 'https://res.cloudinary.com/lightglance/image/upload/v1568980137/photo-1517577968725-c62d5aa5cdb6_xqpffj.jpg' ; %>)">
            <%= link_to ct.name, cocktail_path(ct), class: "text-white" %>
          </div>
        <% end %>
      </div>
      <%= link_to 'Add a cocktail', new_cocktail_path, class: "btn btn-success my-3" %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card-trip">
        <img src=<%= @cocktail.photo.present? ? (cl_image_path @cocktail.photo) : 'https://res.cloudinary.com/lightglance/image/upload/v1568980137/photo-1517577968725-c62d5aa5cdb6_xqpffj.jpg' ; %> alt=<%= @cocktail.name %>>
        <div class="card-trip-infos">
          <div class="d-flex justify-content-between align-items-center">
            <div class="w-50">
              <h2><%= @cocktail.name %></h2>
              <p><%= @cocktail.instructions %></p>
            </div>
            <div>
              <ul class="list-unstyled">
                <% @doses.each do |dose| %>
                  <li><%= dose.description %> - <%= dose.ingredient.name %></li>
                <% end %>
              </ul>
            </div>
            <div>
              <%= link_to 'edit', edit_cocktail_path, class: "btn btn-warning"  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>